### ISSUE TITLE
Add support for VSCode Vex 0.7

### ISSUE THREAD

**Issue by melMass** [cgtoolbox/vscode-houdinivexhelp#2]
Hi Guillaume,

I've been trying a few times to make a fully fledge VEX language server for VSCode, I tried different roads and I'm not entirely satisfied with the current implementation but I want to release a first version: 0.7 soon.

One of the things that this version brings is **help cards** like these:
<p align="center">
<img width="320px" src="https://user-images.githubusercontent.com/7041726/152794913-e00a94f4-0462-4d79-8619-ee872d4b8428.gif"/>
</p>

I parse the documentation from Houdini help files to get these, while they are very useful I was thinking of syncing with you to find a way for the documentation URLs to be handled by your extension, for now it's opening a browser: 
<p align="center">
<img width="320px" src="https://user-images.githubusercontent.com/7041726/152795522-eb870a6b-d1d5-4825-b81c-9f5c7720dd33.gif"/>
</p>

I'm almost ready for the pre-release (beta until v1.0) and would love to add this.

Let me know what you think and if it's something that you'd be up to

Thanks

**Comment by cgtoolbox** [comment]
Hi Mel,

Great stuff you've got here ! But what to you mean by handeling the URLs by my extension ? It also just opens a webbrowser, but from the current cursor position instead of a link. So I don't see much differences with what you've got in the card here ?

I think I'd just deprecate this tool once you have yours at version 1.0 :)

**Comment by melMass** [comment]
Thanks for the prompt reply!

> It also just opens a web browser

My bad, I should have looked at the code before, I though you were using an embedded web view in a VSCode tab, I wanted to avoid doing it but I will 😬
